// frontend/src/layouts/DashboardLayout.vue
<template>
    <div class="flex h-screen bg-gray-100">
        <AppSidebar />
        <div class="flex-1 flex flex-col">
            <AppTopbar />
            <main class="flex-1 overflow-auto p-6">
                <slot />
            </main>
        </div>
        <ToastNotification />
    </div>
</template>

<script setup>
import AppSidebar from '@/components/sidebar/AppSidebar.vue'
import AppTopbar from '@/components/topbar/AppTopbar.vue'
import ToastNotification from '@/components/shared/ToastNotification.vue'
</script>

<style scoped></style>

// frontendreact/src/layouts/DashboardLayout.jsx
import Sidebar from "../components/Sidebar"
import Navbar from "../components/Navbar"
import { Outlet } from "react-router-dom"

export default function DashboardLayout() {
  return (
    <div className="flex min-h-screen w-full bg-gray-100">

      <Sidebar />

      <div className="flex-1 flex flex-col">

        <Navbar />

        <main className="flex-1 p-6">
          <Outlet />
        </main>

      </div>

    </div>
  )
}
